---
# ==========================
# INSTALL AND START JENKINS
# ==========================
- name: Install and start Jenkins
  hosts: jenkins
  become: yes

  tasks:
    - name: Add Jenkins apt repository key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present

    - name: Add Jenkins apt repository
      apt_repository:
        repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
        state: present

    - name: Install Java 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        update_cache: yes
        state: present

    - name: Ensure Jenkins is started and enabled
      service:
        name: jenkins
        state: started
        enabled: yes


# ==========================
# INSTALL HELM AND DATREE
# ==========================
- name: Install Helm and Datree plugin
  hosts: jenkins
  become: yes

  tasks:
    - name: Check if Helm is already installed
      shell: helm version
      register: helm_check
      changed_when: false
      ignore_errors: yes

    - name: Download Helm install script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0755'
      when: helm_check.rc != 0

    - name: Install Helm
      shell: /tmp/get_helm.sh
      when: helm_check.rc != 0

    - name: Install unzip (required for some plugins/tools)
      apt:
        name: unzip
        state: present

    - name: Check if Datree plugin is installed
      shell: helm plugin list | grep datree
      register: datree_check
      failed_when: datree_check.rc != 1 and datree_check.rc != 0
      changed_when: false
      check_mode: no

    - name: Install Datree plugin for Helm
      shell: helm plugin install https://github.com/datreeio/helm-datree
      when: datree_check.rc != 0


# ==========================
# INSTALL DOCKER + KUBECTL
# ==========================
- name: Install Docker and Kubectl tools
  hosts: jenkins
  become: yes

  tasks:
    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker apt repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Add jenkins user to sudo group
      user:
        name: jenkins
        groups: sudo
        append: yes

    - name: Add jenkins user to docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Allow jenkins to run sudo commands without password
      lineinfile:
        path: /etc/sudoers
        line: 'jenkins ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Create kubectl alias for root user
      lineinfile:
        path: /root/.bashrc
        regexp: '^alias k='
        line: 'alias k=kubectl'
        state: present

